cluster:
  mkdir -p logs/{rule} &&
  mkdir -p logs/processed_notebooks &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
    --parsable
default-resources:
  - mem_mb=50000
  - time="06:00:00"
restart-times: 2
max-jobs-per-second: 3
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 3
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True